#==============================================================================
#	NES Sound Driver Libraly
#		Make file
#				A.Waranabe (S.W.)
#==============================================================================

#--listing --list-bytes 255
ASM = ca65
AFLAG = -t none
AFDS  = -D FDS
AVRC6 = -D VRC6
AVRC7 = -D VRC7
AOPLL = -D OPLL
AMMC5 = -D MMC5
AN163 = -D N163
APSG  = -D PSG
AALL  = -D VRC6 -D VRC7 -D MMC5 -D N163 -D PSG -D DPCMBank
AALL2 = -D FDS -D VRC6 -D VRC7 -D MMC5 -D N163 -D PSG -D DPCMBank
AOALL  = -D VRC6 -D OPLL -D MMC5 -D N163 -D PSG

CC = cl65
CFLAG = -t none -Oi -Os -Or -c -l -o

#-m $*.map -vm
LINKER = ld65
LFLAG = -C default.cfg -o
LFLAGALL = -C all.cfg  -o
LFLAGOALL = -C opllall.cfg -o

LIBER = ar65
LIBFLAG = a

PROJ      = nsd
PROJ_FDS  = nsd_fds
PROJ_VRC6 = nsd_vrc6
PROJ_VRC7 = nsd_vrc7
PROJ_OPLL = nsd_opll
PROJ_MMC5 = nsd_mmc5
PROJ_N163 = nsd_n163
PROJ_PSG  = nsd_s5b
PROJ_ALL  = nsd_all
PROJ_ALL2 = nsd_all2
PROJ_OALL  = nsd_oall

LIB      = ../nsd/nsd.lib
LIB_FDS  = ../nsd/nsd_fds.lib
LIB_VRC6 = ../nsd/nsd_vrc6.lib
LIB_VRC7 = ../nsd/nsd_vrc7.lib
LIB_OPLL = ../nsd/nsd_opll.lib
LIB_MMC5 = ../nsd/nsd_mmc5.lib
LIB_N163 = ../nsd/nsd_n163.lib
LIB_PSG  = ../nsd/nsd_s5b.lib
LIB_ALL  = ../nsd/nsd_all.lib
LIB_ALL2 = ../nsd/nsd_all2.lib
LIB_OALL  = ../nsd/nsd_oall.lib

INC_FILES = 

FILES = crt0.s
OFILES = $(FILES:.s=.o)

clean: $(PROJ).bin $(PROJ_FDS).bin $(PROJ_VRC6).bin $(PROJ_VRC7).bin $(PROJ_OPLL).bin $(PROJ_MMC5).bin $(PROJ_N163).bin $(PROJ_PSG).bin $(PROJ_ALL).bin $(PROJ_ALL2).bin $(PROJ_OALL).bin
	@del *.bak
	@del *.o
	@del *.map

all:   $(PROJ).bin $(PROJ_FDS).bin $(PROJ_VRC6).bin $(PROJ_VRC7).bin $(PROJ_OPLL).bin $(PROJ_MMC5).bin $(PROJ_N163).bin $(PROJ_PSG).bin $(PROJ_ALL).bin $(PROJ_ALL2).bin $(PROJ_OALL).bin

$(PROJ).bin : $(FILES) $(INC_FILES) $(LIB)
	@$(ASM) $(AFLAG) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB)

$(PROJ_FDS).bin : $(FILES) $(INC_FILES) $(LIB_FDS)
	@$(ASM) $(AFDS) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_FDS)

$(PROJ_VRC6).bin : $(FILES) $(INC_FILES) $(LIB_VRC6)
	@$(ASM) $(AVRC6) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_VRC6)

$(PROJ_VRC7).bin : $(FILES) $(INC_FILES) $(LIB_VRC7)
	@$(ASM) $(AVRC7) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_VRC7)

$(PROJ_OPLL).bin : $(FILES) $(INC_FILES) $(LIB_OPLL)
	@$(ASM) $(AOPLL) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_OPLL)

$(PROJ_MMC5).bin : $(FILES) $(INC_FILES) $(LIB_MMC5)
	@$(ASM) $(AMMC5) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_MMC5)

$(PROJ_N163).bin : $(FILES) $(INC_FILES) $(LIB_N163)
	@$(ASM) $(AN163) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_N163)

$(PROJ_PSG).bin : $(FILES) $(INC_FILES) $(LIB_PSG)
	@$(ASM) $(APSG) $(FILES)
	@$(LINKER) $(LFLAG) $*.bin $(OFILES) $(LIB_PSG)

$(PROJ_ALL).bin : $(FILES) $(INC_FILES) $(LIB_ALL)
	@$(ASM) $(AALL) $(FILES)
	@$(LINKER) $(LFLAGALL) $*.bin $(OFILES) $(LIB_ALL)

$(PROJ_ALL2).bin : $(FILES) $(INC_FILES) $(LIB_ALL2)
	@$(ASM) $(AALL2) $(FILES)
	@$(LINKER) $(LFLAGALL) $*.bin $(OFILES) $(LIB_ALL2)

$(PROJ_OALL).bin : $(FILES) $(INC_FILES) $(LIB_OALL)
	@$(ASM) $(AOALL) $(FILES)
	@$(LINKER) $(LFLAGOALL) $*.bin $(OFILES) $(LIB_OALL)

