#==============================================================================
#	NES Sound Driver Libraly
#		Make file
#				A.Waranabe (S.W.)
#==============================================================================

ASM = ca65
#--listing --list-bytes 255
AFLAG = -t none
AFDS  = -D FDS
AVRC6 = -D VRC6
AVRC7 = -D VRC7
AMMC5 = -D MMC5
AN163 = -D N163
APSG  = -D PSG
AALL  = -D VRC6 -D VRC7 -D MMC5 -D N163 -D PSG

CC = cc65
CFLAG = -t none

LIBER = ar65
LIBFLAG = a

PROJ      = NSD
PROJ_FDS  = NSD_FDS
PROJ_VRC6 = NSD_VRC6
PROJ_VRC7 = NSD_VRC7
PROJ_MMC5 = NSD_MMC5
PROJ_N163 = NSD_N163
PROJ_PSG  = NSD_s5b
PROJ_ALL  = NSD_ALL

INC_FILES = nsd.inc

FILES = nsd_func.s nsd_main.s nsd_seq.s nsd_env.s nsd_snd.s nsd_math.s nsd_work.s 
OFILES = $(FILES:.s=.o)

clean: $(PROJ).lib $(PROJ_VRC6).lib $(PROJ_VRC7).lib $(PROJ_MMC5).lib $(PROJ_N163).lib $(PROJ_PSG).lib $(PROJ_ALL).lib
	@del *.bak
	@del *.o

all:   $(PROJ).lib $(PROJ_VRC6).lib $(PROJ_VRC7).lib $(PROJ_MMC5).lib $(PROJ_N163).lib $(PROJ_PSG).lib $(PROJ_ALL).lib

$(PROJ).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) nsd_func.s
	@$(ASM) $(AFLAG) nsd_main.s
	@$(ASM) $(AFLAG) nsd_seq.s
	@$(ASM) $(AFLAG) nsd_env.s
	@$(ASM) $(AFLAG) nsd_snd.s
	@$(ASM) $(AFLAG) nsd_math.s
	@$(ASM) $(AFLAG) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

$(PROJ_VRC6).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(AVRC6) nsd_func.s
	@$(ASM) $(AFLAG) $(AVRC6) nsd_main.s
	@$(ASM) $(AFLAG) $(AVRC6) nsd_seq.s
	@$(ASM) $(AFLAG) $(AVRC6) nsd_env.s
	@$(ASM) $(AFLAG) $(AVRC6) nsd_snd.s
	@$(ASM) $(AFLAG) $(AVRC6) nsd_math.s
	@$(ASM) $(AFLAG) $(AVRC6) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

$(PROJ_VRC7).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(AVRC7) nsd_func.s
	@$(ASM) $(AFLAG) $(AVRC7) nsd_main.s
	@$(ASM) $(AFLAG) $(AVRC7) nsd_seq.s
	@$(ASM) $(AFLAG) $(AVRC7) nsd_env.s
	@$(ASM) $(AFLAG) $(AVRC7) nsd_snd.s
	@$(ASM) $(AFLAG) $(AVRC7) nsd_math.s
	@$(ASM) $(AFLAG) $(AVRC7) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

$(PROJ_MMC5).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(AMMC5) nsd_func.s
	@$(ASM) $(AFLAG) $(AMMC5) nsd_main.s
	@$(ASM) $(AFLAG) $(AMMC5) nsd_seq.s
	@$(ASM) $(AFLAG) $(AMMC5) nsd_env.s
	@$(ASM) $(AFLAG) $(AMMC5) nsd_snd.s
	@$(ASM) $(AFLAG) $(AMMC5) nsd_math.s
	@$(ASM) $(AFLAG) $(AMMC5) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

$(PROJ_N163).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(AN163) nsd_func.s
	@$(ASM) $(AFLAG) $(AN163) nsd_main.s
	@$(ASM) $(AFLAG) $(AN163) nsd_seq.s
	@$(ASM) $(AFLAG) $(AN163) nsd_env.s
	@$(ASM) $(AFLAG) $(AN163) nsd_snd.s
	@$(ASM) $(AFLAG) $(AN163) nsd_math.s
	@$(ASM) $(AFLAG) $(AN163) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

$(PROJ_PSG).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(APSG) nsd_func.s
	@$(ASM) $(AFLAG) $(APSG) nsd_main.s
	@$(ASM) $(AFLAG) $(APSG) nsd_seq.s
	@$(ASM) $(AFLAG) $(APSG) nsd_env.s
	@$(ASM) $(AFLAG) $(APSG) nsd_snd.s
	@$(ASM) $(AFLAG) $(APSG) nsd_math.s
	@$(ASM) $(AFLAG) $(APSG) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

$(PROJ_ALL).lib : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(AALL) nsd_func.s
	@$(ASM) $(AFLAG) $(AALL) nsd_main.s
	@$(ASM) $(AFLAG) $(AALL) nsd_seq.s
	@$(ASM) $(AFLAG) $(AALL) nsd_env.s
	@$(ASM) $(AFLAG) $(AALL) nsd_snd.s
	@$(ASM) $(AFLAG) $(AALL) nsd_math.s
	@$(ASM) $(AFLAG) $(AALL) nsd_work.s
	@$(LIBER) $(LIBFLAG) $*.lib $(OFILES)

