#==============================================================================
#	NES Sound Driver Libraly
#		Make file
#				A.Waranabe (S.W.)
#==============================================================================

.SUFFIXES :
.SUFFIXES : .s .c

ASM = ca65
AFLAG = -t none --listing --list-bytes 255

CC = cc65
CFLAG = -t none

LIBER = ar65
LIBFLAG = a

PROJ = NSD

INC_FILES = nsd.inc

FILES = nsd_func.o nsd_main.o nsd_seq.o nsd_env.o nsd_snd.o nsd_math.o nsd_work.o 

clean: $(PROJ).lib
	@del *.bak

all: $(PROJ).lib

$(PROJ).lib : $(FILES) $(INC_FILES)
	@$(LIBER) $(LIBFLAG) $(PROJ).lib $(FILES)

.c.o :
	@$(CC) $(CFLAG) $*.o $<

.s.o :
	@$(ASM) $(AFLAG) $<
