#==============================================================================
#	NES Sound Driver Libraly
#		Make file
#				A.Waranabe (S.W.)
#==============================================================================

.SUFFIXES :
.SUFFIXES : .s .c .mml

ASM = ca65
AFLAG = -t none

CC = cl65
CFLAG = -t none -Oi -Os -Or -c -o

MC = ..\..\bin\nsc
MFLAG = -a

LINKER = ld65
LFLAG = -C nesa.cfg -v -o

LIBER = ar65
LIBFLAG = a

PROJ = test

LIB_FILES = ../../lib/nsd.lib

INC_FILES = 

FILES = crt0.o main.o testmus.o


clean: $(PROJ).nes
	@del *.bak
	@del *.o

all: $(PROJ).nes

$(PROJ).nes : $(FILES) $(INC_FILES) $(LIB_FILES)
	@$(LINKER) $(LFLAG) $(PROJ).nes $(FILES)  $(LIB_FILES)

.mml.o :
	@$(MC) $(MFLAG) $<
	@$(ASM) $(AFLAG) $*.s

.c.o :
	@$(ASM) $(CFLAG) $*.o $<

.s.o :
	@$(ASM) $(AFLAG) $<


