#==============================================================================
#	NES Sound Driver Libraly
#		Make file
#				A.Waranabe (S.W.)
#==============================================================================

TOOL_PASS =	
INC_PASS =	..\..\include\\
LIB_PASS =	..\..\lib\\

include	$(INC_PASS)makefile.mk

########################################
#;	Siurce files
########################################
#;
#;	ソース追加時は、ファイル名を追加してください。
#;	それだけで、プロジェクトに追加されます。
#;

#---------------
#; プロジェクト名
MAIN_PROJ  =	test.nes

#---------------
#; リンカーの設定
CFG_FILE   =	nesc.cfg
MAP_FILE   =	test.map
DBG_FILE   =	test.dbg

#---------------
#; ソースファイル
MAIN_FILES =	test.o

CHR_FILES  =	

MML_FILES  =	testmus.o



#---------------------------------------
#;	Header files
#---------------------------------------
#;
#;	ビルドに依存するヘッダーファイルは、ここに書いてください。
#;

#---------------
#; アセンブリ言語用ヘッダー
INC_FILES =	nsd.inc

#---------------
#; Ｃ言語用ヘッダー
H_FILES  =	nsd.h

#---------------
#; ⊿ＰＣＭファイル
DMC_FILES =	




#---------------------------------------
#;	Library files
#---------------------------------------
#;
#;	ビルドに依存するライブラリファイルは、ここに書いてください。
#;

LIB_FILES =	$(LIB_PASS)nsd.lib



########################################
#;	Build process
########################################

.PHONY: all clean

#---------------
#; Default Target（ここに、ビルドするプロジェクトの一覧を記述する。）
all: $(MAIN_PROJ)


#---------------
#; build of main program
$(MAIN_PROJ) : $(MAIN_FILES) $(CHR_FILES) $(MML_FILES) $(LIB_FILES)
	@echo [Link] : $@ >>$(ERRLOG_FILE)
	$(LINKER) $(LDFLAGS) $@ $^ nes.lib 1>>$(LOG_FILE) 2>>$(ERRLOG_FILE)

#---------------
#; Crean up
clean:
#	@$(RM) *.nes		#NESファイルは、消さないでおく。
	@$(RM) *.bak
	@$(RM) *.map
	@$(RM) *.lst
	@$(RM) *.o

	@$(RM) $(LOG_FILE)
	@$(RM) $(ERRLOG_FILE)
	@$(RM) $(BLDLOG_FILE)
