#==============================================================================
#	NES Sound Driver Libraly
#		Make file
#				A.Waranabe (S.W.)
#==============================================================================

.SUFFIXES :
.SUFFIXES : .s .c

ASM = ca65
AFLAG = -t none --listing --list-bytes 255

CC = cl65
CFLAG = -t none -Oi -Os -Or -c -l -o

LINKER = ld65
LFLAG = -C config.cfg -m $(PROJ).map -vm -o

LIBER = ar65
LIBFLAG = a

PROJ = test

LIB_FILES = ../../lib/nsd.lib

INC_FILES = 

FILES = test.o



clean: $(PROJ).nes
	@del *.bak

all: $(PROJ).nes

$(PROJ).nes : $(FILES) $(INC_FILES) $(LIB_FILES)
	@$(LINKER) $(LFLAG) $(PROJ).nes $(FILES)  $(LIB_FILES) nes.lib

.c.o :
	@$(CC) $(CFLAG) $*.o $<

.s.o :
	@$(ASM) $(AFLAG) $<
